import { useCallback, useEffect, useState } from 'react'
import { Radio, Map as MapIcon, MapPin, FolderOpen, Users, UserRound, LogOut, Plus, Search, ArrowUpRight, SlidersHorizontal, ChevronDown, ShieldCheck, X, ArrowRight, LockKeyhole, RefreshCw, Check, Eye, EyeOff } from 'lucide-react'
import type { LucideIcon } from 'lucide-react'
import type { Data, Kind, Report, User } from './types'
import { api, date, setCsrf } from './api'
import Map from './Map'
import PortalAlerts from './PortalAlerts'
import {useActivePings} from './useActivePings'
import Detail from './Detail'
import './App.css'
import './minimal.css'

type Page='Mappa'|'Segnalazioni'|'Fascicoli'|'Utenti'|'Profilo'
const navigation:{label:Page;icon:LucideIcon}[]=[{label:'Mappa',icon:MapIcon},{label:'Segnalazioni',icon:MapPin},{label:'Fascicoli',icon:FolderOpen}]
const emptyData:Data={reports:[],dossiers:[],users:[],types:[],activity:[],uploadConfig:{maxBytes:10485760,allowed:[]}}
const initials=(name:string)=>name.split(' ').map(s=>s[0]).slice(0,2).join('').toUpperCase()

function Login({onLogin}:{onLogin:(user:User,csrf:string)=>void}) {
  const [login,setLogin]=useState(''),[password,setPassword]=useState(''),[error,setError]=useState(''),[busy,setBusy]=useState(false),[show,setShow]=useState(false)
  return <div className="login-page"><div className="login-right"><div className="login-card"><div className="simple-brand"><Radio size={22}/> RadioLog</div><h2>Bentornato.</h2><p>Accedi per ritrovare le attivit�  del gruppo.</p><form onSubmit={async e=>{e.preventDefault();setBusy(true);setError('');try{const result=await api<{user:User;csrf:string}>('/login',{method:'POST',body:JSON.stringify({login,password})});onLogin(result.user,result.csrf)}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Email<input type="email" autoComplete="username" required value={login} onChange={e=>setLogin(e.target.value)} placeholder="nome@esempio.it"/></label><label>Password<div className="password-field"><input autoComplete="current-password" type={show?'text':'password'} required value={password} onChange={e=>setPassword(e.target.value)} placeholder="La tua password"/><button type="button" aria-label={show?'Nascondi password':'Mostra password'} onClick={()=>setShow(!show)}>{show?<EyeOff size={18}/>:<Eye size={18}/>}</button></div></label><p className="session-hint"><ShieldCheck size={15}/> La sessione rimane attiva per 7 giorni</p>{error&&<p className="error-banner" role="alert">{error}</p>}<button className="button primary login-submit" disabled={busy}>{busy?'Accesso in corso…':'Accedi al tuo spazio'}<ArrowRight size={18}/></button></form><p className="login-help">Non hai un account? Rivolgiti all’amministratore del gruppo.</p></div><footer>Progetto amatoriale privato. Non è un servizio di emergenza.</footer></div></div>
}

export default function App() {
  const [user,setUser]=useState<User|null>(null),[boot,setBoot]=useState(true),[data,setData]=useState<Data>(emptyData),[loading,setLoading]=useState(false)
  const [page,setPage]=useState<Page>('Mappa'),[menu,setMenu]=useState(false),[error,setError]=useState(''),[toast,setToast]=useState('')
  const [search,setSearch]=useState(''),[type,setType]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[author,setAuthor]=useState(''),[status,setStatus]=useState(''),[sort,setSort]=useState('date'),[filters,setFilters]=useState(false)
  const [detail,setDetail]=useState<{kind:Kind;id?:string;position?:[number,number];key:number}|null>(null)
  const load=useCallback(async()=>{setLoading(true);try{setData(await api<Data>('/data'));setError('')}catch(e){setError((e as Error).message)}finally{setLoading(false)}},[])
  useEffect(()=>{api<{user:User;csrf:string}>('/me').then(r=>{setUser(r.user);setCsrf(r.csrf)}).catch(()=>{}).finally(()=>setBoot(false));const expired=()=>{setUser(null);setData(emptyData)};window.addEventListener('session-expired',expired);return()=>window.removeEventListener('session-expired',expired)},[])
  useEffect(()=>{if(user)void load()},[user,load])
  useEffect(()=>{if(!toast)return;const timer=setTimeout(()=>setToast(''),4000);return()=>clearTimeout(timer)},[toast])
  function navigate(next:Page){setPage(next);setMenu(false);setSearch('');setType('');setAuthor('');setStatus('');setFrom('');setTo('');setFilters(false)}
  const open=(kind:Kind,id?:string,position?:[number,number])=>setDetail({kind,id,position,key:Date.now()})
  const inDate=(d:string)=>(!from||d.slice(0,10)>=from)&&(!to||d.slice(0,10)<=to)
  const reports=data.reports.filter(r=>(!type||r.typeId===type)&&(!author||r.authorId===author)&&inDate(r.eventDate)&&`${r.title} ${r.description}`.toLowerCase().includes(search.toLowerCase()))
  const mapReports=useActivePings(reports)
  const dossiers=data.dossiers.filter(d=>(!status||d.status===status)&&(!author||d.authorId===author)&&inDate(d.createdAt)&&`${d.publicCode} ${d.title} ${d.content.replace(/<[^>]+>/g,' ')}`.toLowerCase().includes(search.toLowerCase())).sort((a,b)=>sort==='id'?b.publicCode.localeCompare(a.publicCode):b.updatedAt.localeCompare(a.updatedAt))
  const reportType=(report:Report)=>data.types.find(t=>t.id===report.typeId)
  const filterBar=<div className="filter-bar"><div className="filter-search"><Search size={16}/><input aria-label="Cerca" placeholder={page==='Fascicoli'?'Cerca per ID, titolo o contenuto…':'Cerca una segnalazione…'} value={search} onChange={e=>setSearch(e.target.value)}/></div>{page==='Fascicoli'?<select aria-label="Stato" value={status} onChange={e=>setStatus(e.target.value)}><option value="">Tutti gli stati</option><option value="bozza">Bozza</option><option value="aperto">Aperto</option><option value="chiuso">Chiuso</option></select>:<select aria-label="Tipo di segnalazione" value={type} onChange={e=>setType(e.target.value)}><option value="">Tutti i tipi</option>{data.types.map(t=><option key={t.id} value={t.id}>{t.name}</option>)}</select>}<button className={`button secondary ${filters?'selected':''}`} onClick={()=>setFilters(!filters)}><SlidersHorizontal size={15}/>Filtri{(author||from||to)&&<span className="dot blue"/>}</button>{page==='Fascicoli'&&<select aria-label="Ordina fascicoli" value={sort} onChange={e=>setSort(e.target.value)}><option value="date">Ultima modifica</option><option value="id">Codice ID</option></select>}</div>
  const extraFilters=filters&&<div className="extra-filters"><label>Dal<input aria-label="Data iniziale" type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label>Al<input aria-label="Data finale" type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label><label>Autore<select value={author} onChange={e=>setAuthor(e.target.value)}><option value="">Tutti gli autori</option>{data.users.map(u=><option key={u.id} value={u.id}>{u.username}</option>)}</select></label><button className="text-button" onClick={()=>{setFrom('');setTo('');setAuthor('');setType('');setStatus('');setSearch('')}}>Azzera filtri</button></div>
  if(boot)return <div className="loading-screen"><Radio size={34}/><span>Connessione al tuo spazio…</span></div>
  if(!user)return <Login onLogin={(u,csrf)=>{setCsrf(csrf);setUser(u)}}/>
  return <div className="minimal-app">
    <header className="simple-header">
      <button className="simple-brand" onClick={()=>navigate('Mappa')}><Radio size={23}/>RadioLog</button>
      <nav aria-label="Navigazione principale">{navigation.map(({label,icon:Icon})=><button key={label} className={page===label?'active':''} onClick={()=>navigate(label)}><Icon size={17}/>{label}</button>)}</nav>
      <PortalAlerts userId={user.id}/>
      <div className="account-menu"><button className="account-toggle" aria-label="Menu account" aria-expanded={menu} onClick={()=>setMenu(!menu)}><UserRound size={18}/><span>{user.username}</span><ChevronDown size={14}/></button>{menu&&<div className="account-dropdown"><button onClick={()=>navigate('Profilo')}>Profilo</button>{user.role==='admin'&&<button onClick={()=>navigate('Utenti')}>Utenti</button>}<button onClick={async()=>{try{await api('/logout',{method:'POST'});setUser(null);setData(emptyData);setDetail(null);setMenu(false)}catch(e){setError((e as Error).message)}}}><LogOut size={15}/>Esci dall’account</button></div>}</div>
    </header>
    <main><div className="page-heading"><div><h1>{page}</h1><p>{page==='Mappa'?'Reggio Emilia e provincia':page==='Fascicoli'?'I documenti del gruppo':page==='Segnalazioni'?'Le osservazioni salvate':page==='Utenti'?'Gestisci gli accessi':'Il tuo account'}</p></div>{!['Profilo','Utenti'].includes(page)&&<button className="button primary" onClick={()=>open(page==='Fascicoli'?'dossiers':'reports')}><Plus size={17}/>{page==='Fascicoli'?'Nuovo fascicolo':'Nuova segnalazione'}</button>}</div>
    {error&&<div className="error-banner" role="alert">{error}<button className="text-button" onClick={()=>void load()}>Riprova</button></div>}{loading&&<div className="loading-line" role="status">Aggiornamento dati…</div>}
    {page==='Mappa'&&<section className="panel full-map-panel">{filterBar}{extraFilters}<Map userId={user.id} large reports={mapReports} types={data.types} onSelect={id=>open('reports',id)} onCreate={(lat,lng)=>open('reports',undefined,[lat,lng])}/><div className="map-footer"><strong>{mapReports.length} {mapReports.length===1?'ping attivo':'ping attivi'}</strong><span>Emergenze: 24 ore, 48 ore o permanenti. Lo storico resta in Segnalazioni.</span></div></section>}
    {page==='Segnalazioni'&&<section className="panel">{filterBar}{extraFilters}<div className="table-scroll"><table className="reports-table"><thead><tr><th>Segnalazione</th><th>Tipo</th><th>Località</th><th>Data evento</th><th>Autore</th><th/></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td><button className="table-title" aria-label={r.title} onClick={()=>open('reports',r.id)}>{r.title}<small className="mono">SEG-{r.id.slice(0,8).toUpperCase()}</small><span className="report-locality"><MapPin size={12}/>{r.address||`${r.latitude.toFixed(5)}, ${r.longitude.toFixed(5)}`}</span></button></td><td><span className={`badge ${r.typeId==='emergency'?'red':'blue'}`}>{reportType(r)?.name}</span></td><td>{r.address||`${r.latitude.toFixed(5)}, ${r.longitude.toFixed(5)}`}</td><td>{date(r.eventDate)}</td><td>{r.author}</td><td><button className="icon-button" aria-label={`Apri ${r.title}`} onClick={()=>open('reports',r.id)}><ArrowUpRight size={17}/></button></td></tr>)}</tbody></table></div>{reports.length===0&&<div className="empty"><Search size={28}/><h3>Nessuna segnalazione trovata</h3><p>Modifica i filtri oppure aggiungi la prima osservazione.</p></div>}<div className="table-footer">{reports.length} segnalazioni</div></section>}
    {page==='Fascicoli'&&<><section className="panel">{filterBar}{extraFilters}</section><div className="archive-grid">{dossiers.map(d=><button className="archive-card" key={d.id} onClick={()=>open('dossiers',d.id)}><div className="archive-top"><FolderOpen size={28}/><span className={`status ${d.status}`}>{d.status}</span></div><span className="mono">{d.publicCode}</span><h2>{d.title}</h2><div className="archive-bottom"><span className="avatar tiny">{initials(d.author)}</span><span>{d.author}</span><small>{date(d.updatedAt,true)}</small></div></button>)}</div>{dossiers.length===0&&<div className="panel empty"><FolderOpen size={30}/><h3>Nessun fascicolo trovato</h3><p>Crea un fascicolo o prova a modificare i filtri.</p></div>}</>}
    {page==='Utenti'&&user.role==='admin'&&<UsersPage users={data.users} current={user} reload={load} notify={setToast}/>}
    {page==='Profilo'&&<Profile user={user} notify={setToast} onUpdate={setUser}/>}
    <footer className="app-footer">Spazio privato amatoriale. Le annotazioni non sostituiscono i servizi di emergenza.</footer></main>
    {detail&&<Detail key={detail.key} kind={detail.kind} id={detail.id} position={detail.position} user={user} data={data} onClose={()=>setDetail(null)} onSaved={load} onOpen={open} notify={setToast}/>} {toast&&<div className="toast" role="status"><Check size={18}/>{toast}<button aria-label="Chiudi notifica" onClick={()=>setToast('')}><X size={16}/></button></div>}
  </div>
}

function UsersPage({users,current,reload,notify}:{users:User[];current:User;reload:()=>Promise<void>;notify:(s:string)=>void}) {
  const [adding,setAdding]=useState(false),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  async function change(user:User,role:User['role'],active:boolean){try{await api(`/users/${user.id}`,{method:'PATCH',body:JSON.stringify({role,active})});await reload();notify('Utente aggiornato')}catch(e){setError((e as Error).message)}}
  return <section className="panel users-panel"><div className="section-heading"><h2><Users size={19}/>Membri del gruppo <span>{users.length}</span></h2><button className="button primary" onClick={()=>setAdding(!adding)}><Plus size={16}/>Nuovo utente</button></div>{error&&<p className="error-banner" role="alert">{error}</p>}{adding&&<form className="user-form" onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setBusy(true);setError('');try{await api('/users',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});setAdding(false);await reload();notify('Utente creato')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Username<input name="username" required minLength={3}/></label><label>Email<input name="email" type="email" required/></label><label>Password iniziale<input name="password" type="password" required minLength={12} autoComplete="new-password" placeholder="Almeno 12 caratteri"/></label><label>Ruolo<select name="role"><option value="user">Utente</option><option value="admin">Amministratore</option></select></label><button className="button primary" disabled={busy}>Crea account</button></form>}<div className="table-scroll"><table><thead><tr><th>Utente</th><th>Ruolo</th><th>Accesso</th><th>Azioni</th></tr></thead><tbody>{users.map(u=><tr key={u.id}><td><span className="user-inline"><span className="avatar small">{initials(u.username)}</span>{u.username}{u.id===current.id&&<small>(tu)</small>}</span></td><td><select aria-label={`Ruolo di ${u.username}`} value={u.role} disabled={u.id===current.id} onChange={e=>void change(u,e.target.value as User['role'],!!u.active)}><option value="admin">Amministratore</option><option value="user">Utente</option></select></td><td><span className={`status ${u.active?'aperto':'chiuso'}`}>{u.active?'Attivo':'Disattivato'}</span></td><td>{u.id!==current.id&&<button className="text-button" onClick={()=>{if(confirm(`${u.active?'Disattivare':'Riattivare'} l’accesso di ${u.username}?`))void change(u,u.role,!u.active)}}>{u.active?'Disattiva':'Riattiva'}</button>}</td></tr>)}</tbody></table></div></section>
}
function Profile({user,notify,onUpdate}:{user:User;notify:(s:string)=>void;onUpdate:(user:User)=>void}) {
  const [error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [alias,setAlias]=useState(user.alias||''),[aliasBusy,setAliasBusy]=useState(false),[aliasError,setAliasError]=useState('')
  return <div className="profile-grid"><section className="panel profile-card"><span className="avatar big">{initials(user.username)}</span><h2>{user.username}</h2><p>{user.email}</p><span className="status aperto">{user.role==='admin'?'Amministratore':'Utente'}</span><p className="hint">Nel gruppo dal {date(user.createdAt,true)}</p><form className="detail-form" onSubmit={async e=>{e.preventDefault();setAliasBusy(true);setAliasError('');try{const result=await api<{user:User}>('/profile',{method:'PATCH',body:JSON.stringify({alias})});setAlias(result.user.alias||'');onUpdate(result.user);notify('Alias aggiornato')}catch(e){setAliasError((e as Error).message)}finally{setAliasBusy(false)}}}><label>Alias<input aria-label="Alias" maxLength={40} value={alias} onChange={e=>setAlias(e.target.value)} placeholder="Come vuoi farti chiamare"/></label><p className="hint">Facoltativo, massimo 40 caratteri.</p>{aliasError&&<p className="error-banner" role="alert">{aliasError}</p>}<button className="button primary" disabled={aliasBusy}>{aliasBusy?'Salvataggio?':'Salva alias'}</button></form></section><section className="panel password-card"><h2><LockKeyhole size={20}/>Sicurezza dell’account</h2><p>Aggiorna la password. Le altre sessioni verranno disconnesse.</p><form onSubmit={async e=>{e.preventDefault();const target=e.currentTarget;const form=new FormData(target);setBusy(true);setError('');try{await api('/password',{method:'POST',body:JSON.stringify(Object.fromEntries(form))});target.reset();notify('Password aggiornata')}catch(e){setError((e as Error).message)}finally{setBusy(false)}}}><label>Password attuale<input name="currentPassword" type="password" required autoComplete="current-password"/></label><label>Nuova password<input name="password" type="password" required minLength={12} autoComplete="new-password" placeholder="Almeno 12 caratteri"/></label>{error&&<p role="alert" className="error-banner">{error}</p>}<button className="button primary" disabled={busy}><RefreshCw size={15}/>Aggiorna password</button></form></section></div>
}



