import { lazy, Suspense, useEffect, useRef, useState } from 'react'
import type { ComponentProps } from 'react'
import { X, Save, Pencil, Trash2, Paperclip, Download, FileText, ArrowUpRight, Printer, Clock, MapPin } from 'lucide-react'
import type { Attachment, Activity, Data, Dossier, Kind, Report, User } from './types'
import { api, date } from './api'
const LazyEditor = lazy(()=>import('./Editor'))
function Editor(props:ComponentProps<typeof LazyEditor>) { return <Suspense fallback={<div className="empty compact">Caricamento editor…</div>}><LazyEditor {...props}/></Suspense> }

type Values = { pingDurationHours:24|48|null;title:string;content:string;status:'bozza'|'aperto'|'chiuso';notes:string;description:string;eventDate:string;latitude:number;longitude:number;address:string;typeId:string;dossierId:string|null }
export default function Detail({kind,id,position,data,user,onClose,onSaved,onOpen,notify}:{kind:Kind;id?:string;position?:[number,number];data:Data;user:User;onClose:()=>void;onSaved:()=>Promise<void>;onOpen:(kind:Kind,id:string)=>void;notify:(message:string)=>void}) {
  const existing = (kind==='dossiers'?data.dossiers:data.reports).find(x=>x.id===id)
  const [values,setValues]=useState<Values>(()=>({pingDurationHours:48,title:'',content:'<p></p>',status:'bozza',notes:'',description:'',eventDate:new Date().toISOString(),latitude:position?.[0]||44.698,longitude:position?.[1]||10.632,address:'',typeId:'radio',dossierId:null,...existing}))
  const [editing,setEditing]=useState(!id), [attachments,setAttachments]=useState<Attachment[]>([]), [history,setHistory]=useState<Activity[]>([])
  const [loading,setLoading]=useState(Boolean(id)),[saving,setSaving]=useState(false),[error,setError]=useState(''),[confirmDelete,setConfirmDelete]=useState(false)
  const dialog=useRef<HTMLDialogElement>(null)
  const set=<K extends keyof Values>(key:K,value:Values[K])=>setValues(v=>({...v,[key]:value}))
  useEffect(()=>{dialog.current?.showModal()},[])
  useEffect(()=>{
    if(!id)return
    let active=true
    api<(Dossier|Report)&{attachments:Attachment[];history:Activity[]}>(`/${kind}/${id}`).then(row=>{if(active){setValues(v=>({...v,...row}));setAttachments(row.attachments);setHistory(row.history)}}).catch(e=>{if(active)setError(e.message)}).finally(()=>{if(active)setLoading(false)})
    return ()=>{active=false}
  },[kind,id])
  async function save(form:HTMLFormElement) {
    const fields = Object.fromEntries(new FormData(form))
    const payload = {...values, ...fields, ...(kind==='reports'?{dossierId:fields.dossierId||null}: {})}
    setSaving(true);setError('')
    try {
      const result=await api<{id:string}>(`/${kind}${id?`/${id}`:''}`,{method:id?'PUT':'POST',body:JSON.stringify(payload)})
      await onSaved(); notify('Salvataggio completato'); onOpen(kind,result.id)
    } catch(e) {setError((e as Error).message)} finally {setSaving(false)}
  }
  async function remove() {
    setSaving(true)
    try{await api(`/${kind}/${id}`,{method:'DELETE'});await onSaved();notify('Elemento eliminato');onClose()}catch(e){setError((e as Error).message);setSaving(false)}
  }
  async function upload(file:File) {
    setError('')
    if(file.size>data.uploadConfig.maxBytes || !data.uploadConfig.allowed.includes(file.type) || (kind==='reports'&&!file.type.startsWith('image/'))) {setError('Formato non consentito o dimensione superiore al limite.');return}
    const form=new FormData();form.append('file',file);setSaving(true)
    try{const attachment=await api<Attachment>(`/${kind}/${id}/attachments`,{method:'POST',body:form});setAttachments(a=>[...a,attachment]);await onSaved();notify('Allegato caricato')}catch(e){setError((e as Error).message)}finally{setSaving(false)}
  }
  const isDossier=kind==='dossiers'
  const renderedContent=attachments.reduce((html,item)=>html.replaceAll(`radiolog://attachment/${item.id}`,item.url),values.content)
  const localDate=new Date(new Date(values.eventDate).getTime()-new Date(values.eventDate).getTimezoneOffset()*60000).toISOString().slice(0,16)
  return <dialog ref={dialog} aria-label={isDossier?"Dettagli fascicolo":"Dettagli segnalazione"} className="detail-dialog" onCancel={e=>{e.preventDefault();if(!editing||confirm('Chiudere senza salvare le modifiche?'))onClose()}}><div className="dialog-heading"><span className="eyebrow">{isDossier?'ARCHIVIO / FASCICOLO':'MAPPA / SEGNALAZIONE'}</span><button className="icon-button" aria-label="Chiudi" onClick={()=>{if(!editing||confirm('Chiudere senza salvare le modifiche?'))onClose()}}><X size={20}/></button></div>
    {loading?<div className="empty">Caricamento…</div>:<><div className="detail-title"><span className="mono">{isDossier?(existing as Dossier)?.publicCode||'NUOVO FASCICOLO':id?`SEG-${id.slice(0,8).toUpperCase()}`:'NUOVA SEGNALAZIONE'}</span><h2>{editing?(id?'Modifica':'Nuovo')+(isDossier?' fascicolo':' segnalazione'):values.title}</h2>{!editing&&existing&&<p>Creato da {existing.author} · {date(existing.createdAt)} · Modificato {date(existing.updatedAt)}</p>}</div>
    {error&&<div role="alert" className="error-banner">{error}</div>}
    {editing?<form onSubmit={e=>{e.preventDefault();void save(e.currentTarget)}} className="detail-form"><label>Titolo<input autoFocus required minLength={3} maxLength={180} value={values.title} onChange={e=>set('title',e.target.value)} placeholder={isDossier?'Dai un titolo al fascicolo':'Descrivi brevemente la segnalazione'}/></label>
      {isDossier?<><label>Stato<select name="status" value={values.status} onChange={e=>set('status',e.target.value as Values['status'])}><option value="bozza">Bozza</option><option value="aperto">Aperto</option><option value="chiuso">Chiuso</option></select></label><div className="field-label">Contenuto</div><Editor content={values.content} onChange={html=>set('content',html)} images={attachments.filter(a=>a.mimeType.startsWith('image/'))}/><details className="optional-fields"><summary>Note aggiuntive</summary><label>Note<textarea value={values.notes} onChange={e=>set('notes',e.target.value)}/></label></details></>:<><div className="form-grid"><label>Tipo<select name="typeId" value={values.typeId} onChange={e=>set('typeId',e.target.value)}>{data.types.filter(t=>t.active).map(t=><option value={t.id} key={t.id}>{t.name}</option>)}</select></label><label>Data e ora dell’evento<input type="datetime-local" required value={localDate} onChange={e=>{if(e.target.value)set('eventDate',new Date(e.target.value).toISOString())}}/></label></div>{values.typeId==='emergency'&&<label>Durata sulla mappa<select value={values.pingDurationHours===null?'permanent':values.pingDurationHours} onChange={e=>set('pingDurationHours',e.target.value==='permanent'?null:Number(e.target.value) as 24|48)}><option value="24">24 ore</option><option value="48">48 ore</option><option value="permanent">Permanente</option></select><small>Le ore partono dalla creazione della segnalazione.</small></label>}<label>Descrizione<textarea required minLength={3} rows={4} value={values.description} onChange={e=>set('description',e.target.value)} placeholder="Inserisci le tue osservazioni…"/></label><label>Indirizzo o località<input value={values.address} onChange={e=>set('address',e.target.value)} placeholder="Es. Montecchio Emilia"/></label><details className="optional-fields"><summary>Posizione e fascicolo collegato</summary><div className="form-grid"><label>Latitudine<input type="number" step="any" required min={-90} max={90} value={values.latitude} onChange={e=>set('latitude',Number(e.target.value))}/></label><label>Longitudine<input type="number" step="any" required min={-180} max={180} value={values.longitude} onChange={e=>set('longitude',Number(e.target.value))}/></label></div><label>Fascicolo collegato<select name="dossierId" value={values.dossierId||''} onChange={e=>set('dossierId',e.target.value||null)}><option value="">Nessun fascicolo</option>{data.dossiers.map(d=><option key={d.id} value={d.id}>{d.publicCode} · {d.title}</option>)}</select></label></details></>}
      {!id&&<p className="hint"><Paperclip size={15}/> Salva per aggiungere immagini e documenti.</p>}<div className="dialog-actions"><button type="button" className="button secondary" onClick={()=>{if(confirm('Annullare le modifiche?')){if(id)onOpen(kind,id);else onClose()}}}>Annulla</button><button className="button primary" disabled={saving}><Save size={16}/>{saving?'Salvataggio…':'Salva '+(isDossier?'fascicolo':'segnalazione')}</button></div>
    </form>:<><div className="detail-tools"><button className="button secondary" onClick={()=>setEditing(true)}><Pencil size={15}/>Modifica</button>{isDossier&&<button className="button secondary" onClick={()=>window.print()}><Printer size={15}/>Stampa / PDF</button>}{user.role==='admin'&&<button className="button danger" onClick={()=>setConfirmDelete(true)}><Trash2 size={15}/>Elimina</button>}</div>
      {isDossier?<><span className={`status ${values.status}`}>{values.status}</span><article className="document-view" dangerouslySetInnerHTML={{__html:renderedContent}}/>{values.notes&&<div className="note"><strong>Note aggiuntive</strong><p>{values.notes}</p></div>}<h3>Segnalazioni collegate</h3>{data.reports.filter(r=>r.dossierId===id).length===0?<p className="muted">Nessuna segnalazione collegata. Puoi collegarla dal modulo della segnalazione.</p>:data.reports.filter(r=>r.dossierId===id).map(r=><button className="linked-item" key={r.id} onClick={()=>onOpen('reports',r.id)}><MapPin size={16}/>{r.title}<ArrowUpRight size={16}/></button>)}</>:<><div className="report-meta"><span className={`badge ${values.typeId==='emergency'?'red':'blue'}`}>{data.types.find(t=>t.id===values.typeId)?.name}</span><span><Clock size={14}/>{date(values.eventDate)}</span></div>{values.typeId==='emergency'&&<p className="hint">Durata sulla mappa: {values.pingDurationHours===null?'Permanente':`${values.pingDurationHours} ore dalla creazione`}</p>}<p className="report-description">{values.description}</p><div className="note"><MapPin size={18}/><div><strong>{values.address||'Posizione sulla mappa'}</strong><p>{values.latitude.toFixed(5)}, {values.longitude.toFixed(5)}</p></div></div>{values.dossierId&&<button className="linked-item" onClick={()=>onOpen('dossiers',values.dossierId!)}><FileText size={17}/>{data.dossiers.find(d=>d.id===values.dossierId)?.title}<ArrowUpRight size={16}/></button>}</>}
    </>}
    {id&&<section className="attachments"><div className="section-heading"><h3><Paperclip size={16}/> Allegati <span>{attachments.length}</span></h3><label className="button secondary upload-button">{saving?'Caricamento…':'Aggiungi file'}<input type="file" disabled={saving} accept={data.uploadConfig.allowed.filter(m=>isDossier||m.startsWith('image/')).join(',')} onChange={e=>{if(e.target.files?.[0])void upload(e.target.files[0]);e.target.value=''}}/></label></div><p className="hint">{isDossier?'PNG, JPG, WebP e PDF':'PNG, JPG e WebP'} · massimo {data.uploadConfig.maxBytes/1024/1024} MB per file</p>{attachments.length===0?<div className="empty compact">Nessun allegato. Aggiungi un’immagine o un documento.</div>:attachments.map(a=><div className="attachment" key={a.id}>{a.mimeType.startsWith('image/')?<img src={a.url} alt={a.originalName}/>:<FileText size={28}/>}<div><strong>{a.originalName}</strong><small>{(a.size/1024).toFixed(1)} KB · {date(a.createdAt)}</small></div><a className="icon-button" href={a.downloadUrl} title="Scarica allegato"><Download size={17}/></a>{(user.role==='admin'||a.uploadedBy===user.id)&&<button className="icon-button danger-text" title="Elimina allegato" onClick={async()=>{if(confirm('Eliminare questo allegato?'))try{await api(`/attachments/${a.id}`,{method:'DELETE'});setAttachments(items=>items.filter(x=>x.id!==a.id));notify('Allegato eliminato');await onSaved()}catch(e){setError((e as Error).message)}}}><Trash2 size={16}/></button>}</div>)}</section>}
    {id&&!editing&&<details className="history"><summary>Cronologia delle modifiche</summary>{history.map(h=><div key={h.id}><span className="timeline-dot"/><p><strong>{h.author}</strong> · {h.action}<small>{date(h.createdAt)}</small></p></div>)}</details>}
    {confirmDelete&&<div className="delete-confirm" role="alert"><strong>Eliminare definitivamente questo {isDossier?'fascicolo':'elemento'} e i suoi allegati?</strong><p>Questa operazione non può essere annullata.</p><button className="button secondary" onClick={()=>setConfirmDelete(false)}>Annulla</button><button className="button danger" disabled={saving} onClick={()=>void remove()}>Conferma eliminazione</button></div>}</>}
  </dialog>
}



